server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Obsługa routingu SPA - wszystkie ścieżki kierują do index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache dla plików statycznych
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Wyłączenie logowania dla favicon i robots.txt
    location = /favicon.ico {
    # Try to serve mvm_favicon.png if it exists at the root, otherwise return 404
    try_files /mvm_favicon.png =404;
    log_not_found off;
    access_log off;
    add_header Cache-Control "public, no-transform";
    expires 30d;
}
    location = /robots.txt  { log_not_found off; access_log off; }

    error_page 404 /index.html;
}
